/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnitsRouteImport } from './routes/units'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CurrencyRouteImport } from './routes/currency'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as BmiRouteImport } from './routes/bmi'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const UnitsRoute = UnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrencyRoute = CurrencyRouteImport.update({
  id: '/currency',
  path: '/currency',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BmiRoute = BmiRouteImport.update({
  id: '/bmi',
  path: '/bmi',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bmi': typeof BmiRoute
  '/calculator': typeof CalculatorRoute
  '/currency': typeof CurrencyRoute
  '/privacy': typeof PrivacyRoute
  '/units': typeof UnitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bmi': typeof BmiRoute
  '/calculator': typeof CalculatorRoute
  '/currency': typeof CurrencyRoute
  '/privacy': typeof PrivacyRoute
  '/units': typeof UnitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bmi': typeof BmiRoute
  '/calculator': typeof CalculatorRoute
  '/currency': typeof CurrencyRoute
  '/privacy': typeof PrivacyRoute
  '/units': typeof UnitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bmi'
    | '/calculator'
    | '/currency'
    | '/privacy'
    | '/units'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bmi'
    | '/calculator'
    | '/currency'
    | '/privacy'
    | '/units'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bmi'
    | '/calculator'
    | '/currency'
    | '/privacy'
    | '/units'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BmiRoute: typeof BmiRoute
  CalculatorRoute: typeof CalculatorRoute
  CurrencyRoute: typeof CurrencyRoute
  PrivacyRoute: typeof PrivacyRoute
  UnitsRoute: typeof UnitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currency': {
      id: '/currency'
      path: '/currency'
      fullPath: '/currency'
      preLoaderRoute: typeof CurrencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bmi': {
      id: '/bmi'
      path: '/bmi'
      fullPath: '/bmi'
      preLoaderRoute: typeof BmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BmiRoute: BmiRoute,
  CalculatorRoute: CalculatorRoute,
  CurrencyRoute: CurrencyRoute,
  PrivacyRoute: PrivacyRoute,
  UnitsRoute: UnitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
