/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeightRouteImport } from './routes/weight'
import { Route as UsLoanRouteImport } from './routes/us-loan'
import { Route as UnitsRouteImport } from './routes/units'
import { Route as TemperatureRouteImport } from './routes/temperature'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoanRouteImport } from './routes/loan'
import { Route as LengthRouteImport } from './routes/length'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CurrencyRouteImport } from './routes/currency'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaloriesRouteImport } from './routes/calories'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as BmiRouteImport } from './routes/bmi'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'

const WeightRoute = WeightRouteImport.update({
  id: '/weight',
  path: '/weight',
  getParentRoute: () => rootRouteImport,
} as any)
const UsLoanRoute = UsLoanRouteImport.update({
  id: '/us-loan',
  path: '/us-loan',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsRoute = UnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRouteImport,
} as any)
const TemperatureRoute = TemperatureRouteImport.update({
  id: '/temperature',
  path: '/temperature',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanRoute = LoanRouteImport.update({
  id: '/loan',
  path: '/loan',
  getParentRoute: () => rootRouteImport,
} as any)
const LengthRoute = LengthRouteImport.update({
  id: '/length',
  path: '/length',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrencyRoute = CurrencyRouteImport.update({
  id: '/currency',
  path: '/currency',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaloriesRoute = CaloriesRouteImport.update({
  id: '/calories',
  path: '/calories',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BmiRoute = BmiRouteImport.update({
  id: '/bmi',
  path: '/bmi',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bmi': typeof BmiRoute
  '/calculator': typeof CalculatorRoute
  '/calories': typeof CaloriesRoute
  '/contact': typeof ContactRoute
  '/currency': typeof CurrencyRoute
  '/faq': typeof FaqRoute
  '/length': typeof LengthRoute
  '/loan': typeof LoanRoute
  '/privacy': typeof PrivacyRoute
  '/temperature': typeof TemperatureRoute
  '/units': typeof UnitsRoute
  '/us-loan': typeof UsLoanRoute
  '/weight': typeof WeightRoute
  '/category/$slug': typeof CategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bmi': typeof BmiRoute
  '/calculator': typeof CalculatorRoute
  '/calories': typeof CaloriesRoute
  '/contact': typeof ContactRoute
  '/currency': typeof CurrencyRoute
  '/faq': typeof FaqRoute
  '/length': typeof LengthRoute
  '/loan': typeof LoanRoute
  '/privacy': typeof PrivacyRoute
  '/temperature': typeof TemperatureRoute
  '/units': typeof UnitsRoute
  '/us-loan': typeof UsLoanRoute
  '/weight': typeof WeightRoute
  '/category/$slug': typeof CategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bmi': typeof BmiRoute
  '/calculator': typeof CalculatorRoute
  '/calories': typeof CaloriesRoute
  '/contact': typeof ContactRoute
  '/currency': typeof CurrencyRoute
  '/faq': typeof FaqRoute
  '/length': typeof LengthRoute
  '/loan': typeof LoanRoute
  '/privacy': typeof PrivacyRoute
  '/temperature': typeof TemperatureRoute
  '/units': typeof UnitsRoute
  '/us-loan': typeof UsLoanRoute
  '/weight': typeof WeightRoute
  '/category/$slug': typeof CategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bmi'
    | '/calculator'
    | '/calories'
    | '/contact'
    | '/currency'
    | '/faq'
    | '/length'
    | '/loan'
    | '/privacy'
    | '/temperature'
    | '/units'
    | '/us-loan'
    | '/weight'
    | '/category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bmi'
    | '/calculator'
    | '/calories'
    | '/contact'
    | '/currency'
    | '/faq'
    | '/length'
    | '/loan'
    | '/privacy'
    | '/temperature'
    | '/units'
    | '/us-loan'
    | '/weight'
    | '/category/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bmi'
    | '/calculator'
    | '/calories'
    | '/contact'
    | '/currency'
    | '/faq'
    | '/length'
    | '/loan'
    | '/privacy'
    | '/temperature'
    | '/units'
    | '/us-loan'
    | '/weight'
    | '/category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BmiRoute: typeof BmiRoute
  CalculatorRoute: typeof CalculatorRoute
  CaloriesRoute: typeof CaloriesRoute
  ContactRoute: typeof ContactRoute
  CurrencyRoute: typeof CurrencyRoute
  FaqRoute: typeof FaqRoute
  LengthRoute: typeof LengthRoute
  LoanRoute: typeof LoanRoute
  PrivacyRoute: typeof PrivacyRoute
  TemperatureRoute: typeof TemperatureRoute
  UnitsRoute: typeof UnitsRoute
  UsLoanRoute: typeof UsLoanRoute
  WeightRoute: typeof WeightRoute
  CategorySlugRoute: typeof CategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weight': {
      id: '/weight'
      path: '/weight'
      fullPath: '/weight'
      preLoaderRoute: typeof WeightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/us-loan': {
      id: '/us-loan'
      path: '/us-loan'
      fullPath: '/us-loan'
      preLoaderRoute: typeof UsLoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temperature': {
      id: '/temperature'
      path: '/temperature'
      fullPath: '/temperature'
      preLoaderRoute: typeof TemperatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan': {
      id: '/loan'
      path: '/loan'
      fullPath: '/loan'
      preLoaderRoute: typeof LoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/length': {
      id: '/length'
      path: '/length'
      fullPath: '/length'
      preLoaderRoute: typeof LengthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currency': {
      id: '/currency'
      path: '/currency'
      fullPath: '/currency'
      preLoaderRoute: typeof CurrencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calories': {
      id: '/calories'
      path: '/calories'
      fullPath: '/calories'
      preLoaderRoute: typeof CaloriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bmi': {
      id: '/bmi'
      path: '/bmi'
      fullPath: '/bmi'
      preLoaderRoute: typeof BmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BmiRoute: BmiRoute,
  CalculatorRoute: CalculatorRoute,
  CaloriesRoute: CaloriesRoute,
  ContactRoute: ContactRoute,
  CurrencyRoute: CurrencyRoute,
  FaqRoute: FaqRoute,
  LengthRoute: LengthRoute,
  LoanRoute: LoanRoute,
  PrivacyRoute: PrivacyRoute,
  TemperatureRoute: TemperatureRoute,
  UnitsRoute: UnitsRoute,
  UsLoanRoute: UsLoanRoute,
  WeightRoute: WeightRoute,
  CategorySlugRoute: CategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
